version: '2'
services:

  hadoop-master:
    extends:
      file: base.yml
      service: java-8-base
    image: ${HADOOP_MASTER_IMAGE}
    hostname: hadoop-master
    ports:
      - '${HIVE_PROXY_PORT}:1180'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'
