version: '2'
services:

  java-8-base:
    image: 'teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f'
    volumes:
      - ../..:/docker/volumes/conf

  hadoop-master:
    extends:
      service: java-8-base
    image: 'teradatalabs/cdh5-hive:4'
    hostname: hadoop-master
    ports:
      - '1080:1080'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'

  presto-master:
    extends:
      service: java-8-base
    hostname: presto-master
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh singlenode run
    ports:
      - '8080:8080'
    depends_on:
       - hadoop-master
    volumes:
       - ${PRESTO_SERVER_DIR}:/docker/volumes/presto-server

  application-runner:
    extends:
      service: java-8-base
    hostname: application-runner
    volumes:
      - ${PRESTO_CLI_JAR}:/docker/volumes/presto-cli/presto-cli-executable.jar
      - ${PRODUCT_TESTS_JAR}:/docker/volumes/presto-product-tests/presto-product-tests-executable.jar
      - ../../../conf/tempto/tempto-configuration-for-docker-default.yaml:/docker/volumes/tempto/tempto-configuration-local.yaml
      - ../../../target/test-reports:/docker/volumes/test-reports
