databases:
  hive:
    host: hadoop-master
  presto:
    host: presto-master
    configured_hdfs_user: hive
  cassandra:
    host: cassandra
    port: 9042
    default_schema: test
    table_manager_type: cassandra
